In [2]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=3 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shree\appdata\roaming\python\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\shree\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.4 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/8.1 MB 1.6 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.1 MB 1.7 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.1 MB 1.8 MB/s eta 0:00:04
   --------- ------------------------------ 1.8/8.1 MB 1.7 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.8 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.1 MB 1.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 1.9 MB/s eta 0:00:03
   ------------------ --------------------- 3.7/8.1 MB 1.8 MB/s eta 0:00:03
   ------------------- -------------------- 3.9/8.1 MB 1.8 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.1 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 4.7/8.1 MB 1.8 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.8 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   ------------------------------ --------- 6.3/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 930.0 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 946.2 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 946.2 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 946.2 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 946.2 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 890.0 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 894.8 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 779.7 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 665.4 kB/s  0:00:12
Installing collected packages: matplotlib
Successfully installed matplotlib-3.10.8
Note: you may need to restart the kernel to use updated packages.

'DOSKEY' is not recognized as an internal or external command,
operable program or batch file.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\shree\.conda\envs\py312\python.exe -m pip install --upgrade pip

In [157]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [158]:
prod = pd.read_csv(r"E:\2026\PROJECCTS\Inventory Intelligence\products_export.csv")

In [159]:
cat = pd.read_csv(r"E:\2026\PROJECCTS\Inventory Intelligence\categories_export.csv")

In [160]:
cat['vendor']=cat['Item Sort Order'].str.extract((r'\(([A-Z]+)\)'))

In [161]:
cat.head()

,Category ID,Category Name,Item Sort Order,vendor
0,KNBQ2K17X8TQW,Quick Items,White Reusable T-Shirt Bag (CGD),CGD
1,NaN,NaN,Brown Paper Bag (CGD),CGD
2,NaN,NaN,White Paper Bag,NaN
3,NaN,NaN,Book of Matches (CGD),CGD
4,NaN,NaN,Chapstick: Moisturizer Lip Balm 0.15 oz Stick ...,KUD

In [162]:
cat=cat.rename(columns={'Item Sort Order':'Name'})

In [163]:
cat= cat.drop(columns= ['Category ID','Category Name'], axis=1)

In [164]:
cat.loc[(cat['vendor'].isnull()) & (cat['Name'].str.contains('Frito',na=False)),'vendor']='Frito'

In [165]:
prod['vendor'] = prod['Name'].str.extract((r'\(([A-Z]+)\)'))

In [166]:
prod.loc[(prod['vendor'].isnull()) &(prod['Name'].str.contains('Frito',na=False)),'vendor']="Frito"

In [174]:
toniq=pd.merge(prod,cat, on='Name')

In [175]:
toniq.shape

(33702, 22)

In [169]:
toniq = toniq.to_csv("toniq.csv")

In [176]:
toniq.head()

,Clover ID,Name,Alternate Name,Description,Price,Price Type,Price Unit,Cost,Product Code,SKU,...,Default tax rates?,Non-revenue item?,Printer Labels,Modifier Groups,Categories,Tax Rates,Variant Attribute,Variant Option,vendor_x,vendor_y
0,N4Y8KG8T5PG8P,Idaho Spuds: Mashed Potatoes - Classic 13.3 oz...,NaN,NaN,$3.29,Fixed,NaN,$1.77,011140425004,011140425004,...,Yes,No,NaN,NaN,Groceries,NaN,NaN,NaN,NaN,NaN
1,R6PP2FC4SDPGE,Hunt's: Diced Tomatoes 14.5 oz Can,NaN,NaN,$1.69,Fixed,NaN,$0.62,027000380406,027000380406,...,Yes,No,NaN,NaN,Groceries - Boxed / Canned,NaN,NaN,NaN,NaN,NaN
2,91MTVKH1DVRSE,Hunt's: Tomato Paste 6 oz Can,NaN,NaN,$1.89,Fixed,NaN,$1.00,027000388150,027000388150,...,Yes,No,NaN,NaN,Groceries - Boxed / Canned,NaN,NaN,NaN,NaN,NaN
3,KZZPGWGPW5FM6,JJ's Bakery: Lemon Pie 4 oz,NaN,NaN,$1.29,Fixed,NaN,$0.56,011284003076,011284003076,...,Yes,No,NaN,NaN,Snacks,NaN,NaN,NaN,NaN,NaN
4,AXEPXBXWDH3M8,Spicy Guys: Extra Spicy Pretzels 2.25 oz Bag,NaN,NaN,$2.99,Fixed,NaN,$1.32,810070192099,810070192099,...,Yes,No,NaN,NaN,Snacks - Candy,NaN,NaN,NaN,NaN,NaN